#!/bin/bash

# This file provides an example of how to run STEAK

export OMP_NUM_THREADS=8

NAME=your_file_here.sam
CIGAR_CEILING=1
SMITH_WATERMAN_THRESHOLD=0.95
MINIMAL_TRIMMED_LENGTH=20
REFERENCE_FILE=your_reference.fasta
BAIT_LENGTH=20



steak paired ${NAME} ${CIGAR_CEILING} ${SMITH_WATERMAN_THRESHOLD} ${MINIMAL_TRIMMED_LENGTH} ${REFERENCE_FILE} ${BAIT_LENGTH}

#steak unpaired ${NAME} ${CIGAR_CEILING} ${SMITH_WATERMAN_THRESHOLD} ${MINIMAL_TRIMMED_LENGTH} ${REFERENCE_FILE} ${BAIT_LENGTH}