#!/bin/bash

# This file provides an example of how to run STEAK

export OMP_NUM_THREADS=8

NAME=your_file_here
CIGAR_CEILING=1
SMITH_WATERMAN_THRESHOLD=0.95
MINIMAL_TRIMMED_LENGTH=20
REFERENCE_FILE=your_reference.fasta
BAIT_LENGTH=20


#RUNNING STEAK ON PAIRED-END READS IN SAM FORMAT (sorted by name)
steak paired ${NAME}.sam ${CIGAR_CEILING} ${SMITH_WATERMAN_THRESHOLD} ${MINIMAL_TRIMMED_LENGTH} ${REFERENCE_FILE} ${BAIT_LENGTH}

#RUNNING STEAK ON SINGLE-END READS IN BAM FORMAT piped thru SAMtools
#samtools view ${NAME}.bam | stdbuf -oL steak unpaired ${NAME} ${CIGAR_CEILING} ${SMITH_WATERMAN_THRESHOLD} ${MINIMAL_TRIMMED_LENGTH} ${REFERENCE_FILE} ${BAIT_LENGTH}
